# Generated by Django 6.0.1 on 2026-01-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=250)),
                ('slider_description', models.TextField()),
                ('slider_image', models.ImageField(upload_to='sliders/')),
                ('slider_btn_title', models.CharField(max_length=100)),
                ('slider_btn_link', models.CharField(max_length=100)),
            ],
        ),
    ]
