# Generated by Django 6.0.1 on 2026-02-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermodel',
            name='slider_image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
