# Generated by Django 6.0.1 on 2026-02-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_slidermodel_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=250)),
                ('feature_icon', models.CharField(max_length=250)),
                ('feature_title', models.CharField(max_length=250)),
                ('feature_description', models.TextField()),
            ],
        ),
    ]
