# Generated by Django 6.0.1 on 2026-02-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_featuresmodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturesModels',
            new_name='FeaturesModel',
        ),
    ]
