# Generated by Django 6.0.1 on 2026-02-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_rename_featuresmodels_featuresmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.ImageField(upload_to='static/img/')),
                ('product_weight', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=250)),
                ('product_add_to_cart', models.CharField(max_length=250)),
            ],
        ),
    ]
