# Generated by Django 6.0.1 on 2026-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_productsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionhomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=250)),
                ('about_description', models.TextField()),
                ('about_image', models.ImageField(upload_to='static/img/')),
                ('about_btn_title', models.CharField(max_length=100)),
                ('about_btn_link', models.CharField(max_length=100)),
            ],
        ),
    ]
