# Generated by Django 6.0.1 on 2026-02-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_aboutsectionhomemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonials_star', models.CharField(max_length=250)),
                ('Testimonials_description', models.TextField()),
                ('Testimonials_name_address', models.CharField(max_length=250)),
            ],
        ),
    ]
