# Generated by Django 6.0.1 on 2026-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_productsheromodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductssModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=250)),
                ('hero_subtitle', models.CharField(max_length=250)),
                ('hero_image', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductsHeroModel',
        ),
    ]
