# Generated by Django 6.0.1 on 2026-02-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_productssmodel_delete_productsheromodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductssModel',
        ),
    ]
